utest: Fix gcc 11 compilation error
Volatile qualifiers have been dropped from glib macros.
See merge request GNOME/glib!1719.
Let's drop volatile qualifiers here as well
to fix the following compilation error:
  in expansion of macro 'g_once_init_enter'
  in expansion of macro 'g_atomic_pointer_get'
  argument 2 of '__atomic_load' discards 'volatile' qualifier.

Signed-off-by: Valentine Barshak <valentine.barshak@cogentembedded.com>